os: osx
osx_image: xcode7.3

before_install:
  - wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg -target /
  - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
  - xcrun --toolchain swift
  
script:
  - swift build 
  - swift build -X
  - xcodebuild TOOLCHAINS=swift -scheme HeliumLogger -project HeliumLogger.xcodeproj build test
  - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
