os: osx
osx_image: xcode7.3

before_install:
  - wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-osx.pkg
  
script:
  - swift build 
  - swift test