os: osx
osx_image: xcode7.3

cache:
  directories:
    - /Library/Developer/Toolchains

before_install:
  - wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a/swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-osx.pkg -target /
  - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
  
script:
  - swift build 
  - swift build -X
  - xcodebuild TOOLCHAINS=swift -scheme HeliumLogger -project HeliumLogger.xcodeproj build test -destination 'platform=OS X,arch=x86_64' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
